### ISSUE TITLE
To ensure it is escaped properly

### ISSUE THREAD

**Issue by einhverfr** [ledgersmb/PGObject-Type-ByteString#1]
Will have a pr in shortly, just want a placeholder to let you know I am working on it  on a different computer :-)

**Comment by einhverfr** [comment]
Nice job on the boiler plate, I think I can get it working with a trivial change

**Comment by einhverfr** [comment]
never mind, looks like you have it working>?

**Comment by ehuelsmann** [comment]
I think it actually works now?
